sudo: false
language: node_js
node_js:
- '6'
addons:
  chrome: stable
env:
  global:
  - SAUCE_USERNAME: dojo2-ts-ci
  - SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
  - BROWSERSTACK_USERNAME: dylanschiemann2
  - BROWSERSTACK_ACCESS_KEY: 4Q2g8YAc9qeZzB2hECnS
install:
- travis_retry npm install
script:
- npm run lint
- npm run test:browserstack
- npm run uploadCoverage
- npm run benchmark
