sudo: false
language: node_js
node_js:
  - "0.12"
env:
  global:
    # Please get your own free key if you want to test yourself
    - BROWSERSTACK_USERNAME: dtktestaccount1
    - BROWSERSTACK_ACCESS_KEY: mG2qbEFJCZY2qLsM7yfx
cache:
  directories:
    - node_modules
install:
  - "travis_retry npm install grunt-cli"
  - "travis_retry npm install"
script:
  - "grunt"
  - "grunt intern:node --combined"
  - "grunt intern:remote --combined"
  - "grunt remapIstanbul:ci"
  - "grunt uploadCoverage"
