sudo: false
language: node_js
node_js:
- '6'
env:
  global:
  - SAUCE_USERNAME: dojo2-ts-ci
  - SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
  - BROWSERSTACK_USERNAME: dylanschiemann2
  - BROWSERSTACK_ACCESS_KEY: 2upt88qsxsqqeukQvecu
install:
- travis_retry npm install grunt-cli
- travis_retry npm install
script:
- grunt
- grunt intern:node --combined
- grunt intern:browserstack --combined
- grunt remapIstanbul:ci
- grunt uploadCoverage
notifications:
  slack:
    secure: dX7YuO/IfBUiQFaQIBIYfgsB20hJelbthkOck9qv8BeLOYVTHb90m4xewBfzSW2BEer4O1rc9NkXhAgpvofgYrb80lE0F4bQqK96s1s3WqsE9zbhaG6fOtfeFfCilnNzAr9HlF7EzuQ606p7F81U51z6jWwa+nWGRDqahdOUJsGQAgO2liatS7jUlwGn1N8KtTKZyOlu3B8UN5sgPdakhPZbfWDY7isFnJoiw5NsPR9tIi0JL8HjgoQBV2IGyJqggw2sTQffWnEehoDC+rX2t8GwPYGRxdo4YcFPTZ1XKYixLO6EsWO76ay27jcwrW4cDsUJDx4GYhK/peI+wouFrd9NzL4rU6SEu6F0DroBWFUXs54L5SSZjynth3QZZLORShro607MpMjApql5LrLZzc1Ac7SdBfF4SzVC2JDIUTyUUyi/wXlVQN7TbMY5Emprn1P2NiP/5kVMTBnfNWIBb5hT5HxEg6JJafXMql7GZfjWJZTxvqbIUoyPkijZp7s5lOAA6p7jlcC2HjlnaCI9vIhgcivKSwmbFyRIBMDcZa1z6jojMApcQyBgGRNuLGD0BNFMLeNzPOOO3m3QZHUJl41BAhsvAn4YGKRKVcmcv/qBGTHtF01UZKHX7sE7Fpu3htCOprbicXfROuflOAko17tMb5o8MbzSwu4NYq+CjBA=
